# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-11 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(default='', max_length=30, verbose_name='\u533f\u540d'),
        ),
    ]
