# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-11 14:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 11, 22, 15, 6, 708000), verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateField(default=datetime.datetime(2017, 1, 11, 22, 15, 6, 707000)),
        ),
    ]
